// auto-generated by Codex Directive 07 — Input Map
export const inputMap = {
  keyboard: {
    selectRange: ["Shift+Click", "Shift+Arrow"],
    addSelection: ["Ctrl+Click", "Cmd+Click"],
    toggleVisibility: ["Ctrl+H", "Cmd+H"],
    focusSearch: ["Ctrl+F", "Cmd+F"],
    undo: ["Ctrl+Z", "Cmd+Z"],
    redo: ["Ctrl+Shift+Z", "Cmd+Shift+Z"],
    duplicate: ["Ctrl+D", "Cmd+D"],
    delete: ["Delete", "Backspace"],
    toggleMode: ["Tab"],
  },
  mouse: {
    primary: "Left Button",
    secondary: "Right Button",
    pan: "Middle Button Drag",
    zoom: "Wheel Scroll",
    orbit: "Right Button Drag",
    contextMenu: "Right Button Click",
  },
  touch: {
    orbit: "Single finger drag",
    pan: "Two finger drag",
    zoom: "Pinch",
    select: "Tap",
    contextMenu: "Long press",
  },
  gamepad: {
    orbit: "Right stick",
    pan: "Left stick",
    zoom: "Triggers",
    confirm: "A / Cross",
    cancel: "B / Circle",
  },
};

export default inputMap;
