// auto-generated by Codex Directive 06 — UI Tokens
export const tokens = {
  color: {
    background: "#0f1115",
    surface: "#161a20",
    surfaceRaised: "#1f252d",
    surfaceHover: "#2a313b",
    primary: "#4dabf7",
    primaryHover: "#74c0fc",
    accent: "#ff8787",
    success: "#51cf66",
    warning: "#fcc419",
    danger: "#ff6b6b",
    outline: "#2c333c",
    textPrimary: "#f8f9fa",
    textSecondary: "#ced4da",
    textMuted: "#868e96",
  },
  spacing: {
    none: 0,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 12,
    pill: 999,
  },
  typography: {
    fontFamily: "'Inter', 'Roboto', 'Helvetica Neue', Arial, sans-serif",
    monoFamily: "'Fira Code', 'SFMono-Regular', Consolas, monospace",
    sizeXs: 10,
    sizeSm: 12,
    sizeMd: 14,
    sizeLg: 18,
    sizeXl: 24,
    lineTight: 1.2,
    lineDefault: 1.5,
  },
  elevation: {
    flat: "none",
    raised: "0 6px 16px rgba(15, 17, 21, 0.45)",
    overlay: "0 8px 32px rgba(17, 20, 26, 0.6)",
  },
  transitions: {
    fast: "120ms ease-out",
    normal: "200ms ease-in-out",
    slow: "320ms ease-in",
  },
};

export default tokens;
